import { Employee, Department } from '@/types/employee';

export const mockEmployees: Employee[] = [
  {
    id: 'EMP001',
    name: 'John Smith',
    email: 'john.smith@company.com',
    department: 'Engineering',
    role: 'Senior Developer',
    employeeNumber: 'E001',
    joinDate: '2023-01-15',
    phoneNumber: '+1 (555) 123-4567',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 8, remaining: 12 },
      { leaveType: 'Sick Leave', total: 10, used: 2, remaining: 8 },
      { leaveType: 'Personal Leave', total: 5, used: 1, remaining: 4 },
    ],
  },
  {
    id: 'EMP002',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    department: 'Design',
    role: 'UI/UX Designer',
    employeeNumber: 'E002',
    joinDate: '2022-06-10',
    phoneNumber: '+1 (555) 234-5678',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 15, remaining: 5 },
      { leaveType: 'Sick Leave', total: 10, used: 3, remaining: 7 },
      { leaveType: 'Personal Leave', total: 5, used: 2, remaining: 3 },
    ],
  },
  {
    id: 'EMP003',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    department: 'Engineering',
    role: 'Frontend Developer',
    employeeNumber: 'E003',
    joinDate: '2023-03-20',
    phoneNumber: '+1 (555) 345-6789',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 5, remaining: 15 },
      { leaveType: 'Sick Leave', total: 10, used: 1, remaining: 9 },
      { leaveType: 'Personal Leave', total: 5, used: 0, remaining: 5 },
    ],
  },
  {
    id: 'EMP004',
    name: 'Emily Davis',
    email: 'emily.davis@company.com',
    department: 'Marketing',
    role: 'Marketing Manager',
    employeeNumber: 'E004',
    joinDate: '2021-09-05',
    phoneNumber: '+1 (555) 456-7890',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 10, remaining: 10 },
      { leaveType: 'Sick Leave', total: 10, used: 4, remaining: 6 },
      { leaveType: 'Personal Leave', total: 5, used: 3, remaining: 2 },
    ],
  },
  {
    id: 'EMP005',
    name: 'David Wilson',
    email: 'david.wilson@company.com',
    department: 'HR',
    role: 'HR Manager',
    employeeNumber: 'E005',
    joinDate: '2020-04-12',
    phoneNumber: '+1 (555) 567-8901',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 12, remaining: 8 },
      { leaveType: 'Sick Leave', total: 10, used: 2, remaining: 8 },
      { leaveType: 'Personal Leave', total: 5, used: 1, remaining: 4 },
    ],
  },
  {
    id: 'EMP006',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@company.com',
    department: 'Sales',
    role: 'Sales Representative',
    employeeNumber: 'E006',
    joinDate: '2023-07-01',
    phoneNumber: '+1 (555) 678-9012',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 4, remaining: 16 },
      { leaveType: 'Sick Leave', total: 10, used: 0, remaining: 10 },
      { leaveType: 'Personal Leave', total: 5, used: 1, remaining: 4 },
    ],
  },
  {
    id: 'EMP007',
    name: 'Robert Taylor',
    email: 'robert.taylor@company.com',
    department: 'Engineering',
    role: 'Backend Developer',
    employeeNumber: 'E007',
    joinDate: '2022-11-15',
    phoneNumber: '+1 (555) 789-0123',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 7, remaining: 13 },
      { leaveType: 'Sick Leave', total: 10, used: 3, remaining: 7 },
      { leaveType: 'Personal Leave', total: 5, used: 2, remaining: 3 },
    ],
  },
  {
    id: 'EMP008',
    name: 'Jennifer Martinez',
    email: 'jennifer.martinez@company.com',
    department: 'Design',
    role: 'Graphic Designer',
    employeeNumber: 'E008',
    joinDate: '2023-02-28',
    phoneNumber: '+1 (555) 890-1234',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 6, remaining: 14 },
      { leaveType: 'Sick Leave', total: 10, used: 1, remaining: 9 },
      { leaveType: 'Personal Leave', total: 5, used: 0, remaining: 5 },
    ],
  },
  {
    id: 'EMP009',
    name: 'James Brown',
    email: 'james.brown@company.com',
    department: 'Finance',
    role: 'Financial Analyst',
    employeeNumber: 'E009',
    joinDate: '2021-12-01',
    phoneNumber: '+1 (555) 901-2345',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 11, remaining: 9 },
      { leaveType: 'Sick Leave', total: 10, used: 5, remaining: 5 },
      { leaveType: 'Personal Leave', total: 5, used: 2, remaining: 3 },
    ],
  },
  {
    id: 'EMP010',
    name: 'Maria Garcia',
    email: 'maria.garcia@company.com',
    department: 'Customer Support',
    role: 'Support Specialist',
    employeeNumber: 'E010',
    joinDate: '2023-05-10',
    phoneNumber: '+1 (555) 012-3456',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 3, remaining: 17 },
      { leaveType: 'Sick Leave', total: 10, used: 2, remaining: 8 },
      { leaveType: 'Personal Leave', total: 5, used: 1, remaining: 4 },
    ],
  },
  {
    id: 'EMP011',
    name: 'William Lee',
    email: 'william.lee@company.com',
    department: 'Engineering',
    role: 'DevOps Engineer',
    employeeNumber: 'E011',
    joinDate: '2022-08-22',
    phoneNumber: '+1 (555) 123-7890',
    status: 'on-leave',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 18, remaining: 2 },
      { leaveType: 'Sick Leave', total: 10, used: 4, remaining: 6 },
      { leaveType: 'Personal Leave', total: 5, used: 3, remaining: 2 },
    ],
  },
  {
    id: 'EMP012',
    name: 'Amanda White',
    email: 'amanda.white@company.com',
    department: 'Marketing',
    role: 'Content Writer',
    employeeNumber: 'E012',
    joinDate: '2023-04-01',
    phoneNumber: '+1 (555) 234-8901',
    status: 'active',
    leaveBalances: [
      { leaveType: 'Annual Leave', total: 20, used: 5, remaining: 15 },
      { leaveType: 'Sick Leave', total: 10, used: 1, remaining: 9 },
      { leaveType: 'Personal Leave', total: 5, used: 0, remaining: 5 },
    ],
  },
];

export const mockDepartments: Department[] = [
  { id: 'DEPT001', name: 'Engineering', managerName: 'John Smith', employeeCount: 4 },
  { id: 'DEPT002', name: 'Design', managerName: 'Sarah Johnson', employeeCount: 2 },
  { id: 'DEPT003', name: 'Marketing', managerName: 'Emily Davis', employeeCount: 2 },
  { id: 'DEPT004', name: 'HR', managerName: 'David Wilson', employeeCount: 1 },
  { id: 'DEPT005', name: 'Sales', managerName: 'Lisa Anderson', employeeCount: 1 },
  { id: 'DEPT006', name: 'Finance', managerName: 'James Brown', employeeCount: 1 },
  { id: 'DEPT007', name: 'Customer Support', managerName: 'Maria Garcia', employeeCount: 1 },
];
