import { LeaveRequest } from '@/types/employee';
import { addDays, format, subDays } from 'date-fns';

const today = new Date();

export const mockLeaveRequests: LeaveRequest[] = [
  // Pending Requests
  {
    id: 'LR001',
    employeeId: 'EMP003',
    employeeName: 'Michael Chen',
    leaveType: 'Annual Leave',
    startDate: format(addDays(today, 10), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 12), 'yyyy-MM-dd'),
    days: 3,
    isHalfDay: false,
    status: 'pending',
    reason: 'Family vacation',
    appliedDate: format(subDays(today, 2), 'yyyy-MM-dd'),
  },
  {
    id: 'LR002',
    employeeId: 'EMP006',
    employeeName: 'Lisa Anderson',
    leaveType: 'Personal Leave',
    startDate: format(addDays(today, 5), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 5), 'yyyy-MM-dd'),
    days: 0.5,
    isHalfDay: true,
    status: 'pending',
    reason: 'Medical appointment',
    appliedDate: format(subDays(today, 1), 'yyyy-MM-dd'),
  },
  {
    id: 'LR003',
    employeeId: 'EMP008',
    employeeName: 'Jennifer Martinez',
    leaveType: 'Sick Leave',
    startDate: format(addDays(today, 1), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 2), 'yyyy-MM-dd'),
    days: 2,
    isHalfDay: false,
    status: 'pending',
    reason: 'Flu symptoms',
    appliedDate: format(today, 'yyyy-MM-dd'),
  },
  {
    id: 'LR004',
    employeeId: 'EMP012',
    employeeName: 'Amanda White',
    leaveType: 'Annual Leave',
    startDate: format(addDays(today, 15), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 19), 'yyyy-MM-dd'),
    days: 5,
    isHalfDay: false,
    status: 'pending',
    reason: 'Wedding to attend',
    appliedDate: format(subDays(today, 3), 'yyyy-MM-dd'),
  },

  // Approved Requests
  {
    id: 'LR005',
    employeeId: 'EMP002',
    employeeName: 'Sarah Johnson',
    leaveType: 'Annual Leave',
    startDate: format(subDays(today, 5), 'yyyy-MM-dd'),
    endDate: format(subDays(today, 3), 'yyyy-MM-dd'),
    days: 3,
    isHalfDay: false,
    status: 'approved',
    reason: 'Personal matter',
    appliedDate: format(subDays(today, 10), 'yyyy-MM-dd'),
    approvedBy: 'David Wilson',
    approvedDate: format(subDays(today, 8), 'yyyy-MM-dd'),
  },
  {
    id: 'LR006',
    employeeId: 'EMP011',
    employeeName: 'William Lee',
    leaveType: 'Annual Leave',
    startDate: format(subDays(today, 2), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 5), 'yyyy-MM-dd'),
    days: 7,
    isHalfDay: false,
    status: 'approved',
    reason: 'Summer vacation',
    appliedDate: format(subDays(today, 15), 'yyyy-MM-dd'),
    approvedBy: 'David Wilson',
    approvedDate: format(subDays(today, 12), 'yyyy-MM-dd'),
  },
  {
    id: 'LR007',
    employeeId: 'EMP004',
    employeeName: 'Emily Davis',
    leaveType: 'Personal Leave',
    startDate: format(addDays(today, 8), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 8), 'yyyy-MM-dd'),
    days: 1,
    isHalfDay: false,
    status: 'approved',
    reason: 'Moving house',
    appliedDate: format(subDays(today, 4), 'yyyy-MM-dd'),
    approvedBy: 'David Wilson',
    approvedDate: format(subDays(today, 3), 'yyyy-MM-dd'),
  },
  {
    id: 'LR008',
    employeeId: 'EMP001',
    employeeName: 'John Smith',
    leaveType: 'Annual Leave',
    startDate: format(addDays(today, 20), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 24), 'yyyy-MM-dd'),
    days: 5,
    isHalfDay: false,
    status: 'approved',
    reason: 'Holiday trip',
    appliedDate: format(subDays(today, 7), 'yyyy-MM-dd'),
    approvedBy: 'David Wilson',
    approvedDate: format(subDays(today, 5), 'yyyy-MM-dd'),
  },
  {
    id: 'LR009',
    employeeId: 'EMP007',
    employeeName: 'Robert Taylor',
    leaveType: 'Sick Leave',
    startDate: format(subDays(today, 15), 'yyyy-MM-dd'),
    endDate: format(subDays(today, 14), 'yyyy-MM-dd'),
    days: 2,
    isHalfDay: false,
    status: 'approved',
    reason: 'Common cold',
    appliedDate: format(subDays(today, 16), 'yyyy-MM-dd'),
    approvedBy: 'David Wilson',
    approvedDate: format(subDays(today, 16), 'yyyy-MM-dd'),
  },
  {
    id: 'LR010',
    employeeId: 'EMP009',
    employeeName: 'James Brown',
    leaveType: 'Personal Leave',
    startDate: format(addDays(today, 30), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 30), 'yyyy-MM-dd'),
    days: 0.5,
    isHalfDay: true,
    status: 'approved',
    reason: 'Bank appointment',
    appliedDate: format(subDays(today, 5), 'yyyy-MM-dd'),
    approvedBy: 'David Wilson',
    approvedDate: format(subDays(today, 4), 'yyyy-MM-dd'),
  },

  // Rejected Requests
  {
    id: 'LR011',
    employeeId: 'EMP005',
    employeeName: 'David Wilson',
    leaveType: 'Annual Leave',
    startDate: format(addDays(today, 7), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 11), 'yyyy-MM-dd'),
    days: 5,
    isHalfDay: false,
    status: 'rejected',
    reason: 'Conference attendance',
    appliedDate: format(subDays(today, 6), 'yyyy-MM-dd'),
  },
  {
    id: 'LR012',
    employeeId: 'EMP010',
    employeeName: 'Maria Garcia',
    leaveType: 'Personal Leave',
    startDate: format(addDays(today, 3), 'yyyy-MM-dd'),
    endDate: format(addDays(today, 4), 'yyyy-MM-dd'),
    days: 2,
    isHalfDay: false,
    status: 'rejected',
    reason: 'Personal reasons',
    appliedDate: format(subDays(today, 2), 'yyyy-MM-dd'),
  },
];
