import { Ticket } from '@/types/ticket';

const now = new Date();
const oneHourAgo = new Date(now.getTime() - 60 * 60 * 1000);
const oneDayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);
const fourDaysAgo = new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000);
const fiveDaysAgo = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000);
const sixDaysAgo = new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000);

const addHours = (date: Date, hours: number) => new Date(date.getTime() + hours * 60 * 60 * 1000);
const addDays = (date: Date, days: number) => new Date(date.getTime() + days * 24 * 60 * 60 * 1000);

export const mockTickets: Ticket[] = [
  {
    id: '1',
    ticketNumber: 'TKT-001',
    title: 'Login page not loading on mobile',
    description: 'The login page is completely blank on mobile devices. Users cannot access the app.',
    status: 'new',
    priority: 'critical',
    category: 'bug',
    tags: ['mobile', 'urgent', 'authentication'],
    customerName: 'John Smith',
    customerEmail: 'john.smith@company.com',
    assignedTo: 'user-1',
    assignedToName: 'Sarah Chen',
    createdAt: oneHourAgo.toISOString(),
    updatedAt: oneHourAgo.toISOString(),
    dueDate: addHours(oneHourAgo, 4).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: null,
    responseTime: null,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '2',
    ticketNumber: 'TKT-002',
    title: 'Feature request: Dark mode',
    description: 'Users are requesting a dark mode option for the dashboard.',
    status: 'in_progress',
    priority: 'medium',
    category: 'feature',
    tags: ['ui', 'enhancement', 'popular-request'],
    customerName: 'Emma Wilson',
    customerEmail: 'emma.wilson@techcorp.com',
    assignedTo: 'user-2',
    assignedToName: 'Michael Johnson',
    createdAt: threeDaysAgo.toISOString(),
    updatedAt: oneDayAgo.toISOString(),
    dueDate: addDays(threeDaysAgo, 2).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: addHours(threeDaysAgo, 2).toISOString(),
    responseTime: 120,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '3',
    ticketNumber: 'TKT-003',
    title: 'Database connection timeout',
    description: 'Getting timeout errors when trying to fetch user data.',
    status: 'resolved',
    priority: 'high',
    category: 'bug',
    tags: ['backend', 'critical-system'],
    customerName: 'Alex Brown',
    customerEmail: 'alex.brown@startup.io',
    assignedTo: 'user-3',
    assignedToName: 'David Lee',
    createdAt: fourDaysAgo.toISOString(),
    updatedAt: twoDaysAgo.toISOString(),
    dueDate: addDays(fourDaysAgo, 1).toISOString(),
    resolvedAt: twoDaysAgo.toISOString(),
    closedAt: null,
    firstResponseAt: addHours(fourDaysAgo, 1).toISOString(),
    responseTime: 60,
    resolutionTime: 3 * 24 * 60,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '4',
    ticketNumber: 'TKT-004',
    title: 'How to reset password?',
    description: 'I forgot my password and need to reset it.',
    status: 'waiting',
    priority: 'medium',
    category: 'support',
    tags: ['account', 'support'],
    customerName: 'Sarah Davis',
    customerEmail: 'sarah.d@example.com',
    assignedTo: null,
    assignedToName: null,
    createdAt: twoDaysAgo.toISOString(),
    updatedAt: oneDayAgo.toISOString(),
    dueDate: addDays(twoDaysAgo, 2).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: addHours(twoDaysAgo, 3).toISOString(),
    responseTime: 180,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '5',
    ticketNumber: 'TKT-005',
    title: 'Billing invoice incorrect',
    description: 'The invoice for last month shows wrong charges.',
    status: 'in_progress',
    priority: 'high',
    category: 'billing',
    tags: ['billing', 'finance'],
    customerName: 'Robert Martinez',
    customerEmail: 'robert.m@business.com',
    assignedTo: 'user-1',
    assignedToName: 'Sarah Chen',
    createdAt: fiveDaysAgo.toISOString(),
    updatedAt: oneDayAgo.toISOString(),
    dueDate: addDays(fiveDaysAgo, 1).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: addHours(fiveDaysAgo, 2).toISOString(),
    responseTime: 120,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '6',
    ticketNumber: 'TKT-006',
    title: 'Slow performance on reports page',
    description: 'Report page takes 30+ seconds to load.',
    status: 'closed',
    priority: 'medium',
    category: 'bug',
    tags: ['performance', 'optimization'],
    customerName: 'Jennifer Lee',
    customerEmail: 'jen.lee@company.com',
    assignedTo: 'user-2',
    assignedToName: 'Michael Johnson',
    createdAt: sixDaysAgo.toISOString(),
    updatedAt: threeDaysAgo.toISOString(),
    dueDate: addDays(sixDaysAgo, 3).toISOString(),
    resolvedAt: threeDaysAgo.toISOString(),
    closedAt: threeDaysAgo.toISOString(),
    firstResponseAt: addHours(sixDaysAgo, 1).toISOString(),
    responseTime: 60,
    resolutionTime: 4 * 24 * 60,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '7',
    ticketNumber: 'TKT-007',
    title: 'Cannot delete user account',
    description: 'Getting error when trying to delete my account.',
    status: 'new',
    priority: 'high',
    category: 'account',
    tags: ['account', 'bug', 'urgent'],
    customerName: 'Tom Wilson',
    customerEmail: 'tom.w@domain.com',
    assignedTo: null,
    assignedToName: null,
    createdAt: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
    dueDate: addHours(new Date(now.getTime() - 30 * 60 * 1000), 24).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: null,
    responseTime: null,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '8',
    ticketNumber: 'TKT-008',
    title: 'Export data to CSV not working',
    description: 'The export button on dashboard is not generating CSV file.',
    status: 'in_progress',
    priority: 'medium',
    category: 'bug',
    tags: ['feature', 'export'],
    customerName: 'Lisa Anderson',
    customerEmail: 'lisa.a@company.com',
    assignedTo: 'user-3',
    assignedToName: 'David Lee',
    createdAt: oneDayAgo.toISOString(),
    updatedAt: oneDayAgo.toISOString(),
    dueDate: addDays(oneDayAgo, 2).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: addHours(oneDayAgo, 1).toISOString(),
    responseTime: 60,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '9',
    ticketNumber: 'TKT-009',
    title: 'API rate limiting exceeded',
    description: 'Getting 429 errors when making multiple API calls.',
    status: 'resolved',
    priority: 'high',
    category: 'support',
    tags: ['api', 'technical'],
    customerName: 'Mark Johnson',
    customerEmail: 'mark.j@dev.com',
    assignedTo: 'user-1',
    assignedToName: 'Sarah Chen',
    createdAt: threeDaysAgo.toISOString(),
    updatedAt: oneDayAgo.toISOString(),
    dueDate: addDays(threeDaysAgo, 1).toISOString(),
    resolvedAt: oneDayAgo.toISOString(),
    closedAt: null,
    firstResponseAt: addHours(threeDaysAgo, 1).toISOString(),
    responseTime: 60,
    resolutionTime: 2 * 24 * 60,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '10',
    ticketNumber: 'TKT-010',
    title: 'Add webhook support',
    description: 'Users want webhook notifications for order updates.',
    status: 'new',
    priority: 'low',
    category: 'feature',
    tags: ['webhook', 'integration', 'feature-request'],
    customerName: 'Chris Taylor',
    customerEmail: 'chris.t@startup.com',
    assignedTo: null,
    assignedToName: null,
    createdAt: fiveDaysAgo.toISOString(),
    updatedAt: fiveDaysAgo.toISOString(),
    dueDate: addDays(fiveDaysAgo, 7).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: null,
    responseTime: null,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '11',
    ticketNumber: 'TKT-011',
    title: 'Overdue: Payment processing delayed',
    description: 'Payments are taking longer than expected to process.',
    status: 'in_progress',
    priority: 'critical',
    category: 'billing',
    tags: ['critical', 'payments', 'overdue'],
    customerName: 'Patricia Moore',
    customerEmail: 'patricia.m@commerce.com',
    assignedTo: 'user-2',
    assignedToName: 'Michael Johnson',
    createdAt: fiveDaysAgo.toISOString(),
    updatedAt: threeDaysAgo.toISOString(),
    dueDate: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: addHours(fiveDaysAgo, 1).toISOString(),
    responseTime: 60,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '12',
    ticketNumber: 'TKT-012',
    title: 'User profile picture not uploading',
    description: 'Cannot upload profile picture, getting size error.',
    status: 'waiting',
    priority: 'low',
    category: 'support',
    tags: ['upload', 'profile'],
    customerName: 'Kevin Brown',
    customerEmail: 'kevin.b@email.com',
    assignedTo: null,
    assignedToName: null,
    createdAt: fourDaysAgo.toISOString(),
    updatedAt: twoDaysAgo.toISOString(),
    dueDate: addDays(fourDaysAgo, 3).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: addHours(fourDaysAgo, 2).toISOString(),
    responseTime: 120,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '13',
    ticketNumber: 'TKT-013',
    title: 'Implement two-factor authentication',
    description: 'Add 2FA support for enhanced security.',
    status: 'new',
    priority: 'high',
    category: 'feature',
    tags: ['security', 'feature', 'authentication'],
    customerName: 'Nancy Garcia',
    customerEmail: 'nancy.g@secure.com',
    assignedTo: null,
    assignedToName: null,
    createdAt: sixDaysAgo.toISOString(),
    updatedAt: sixDaysAgo.toISOString(),
    dueDate: addDays(sixDaysAgo, 5).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: null,
    responseTime: null,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '14',
    ticketNumber: 'TKT-014',
    title: 'Email notifications not received',
    description: 'Not getting email alerts for important updates.',
    status: 'in_progress',
    priority: 'medium',
    category: 'bug',
    tags: ['email', 'notifications'],
    customerName: 'Daniel Rodriguez',
    customerEmail: 'daniel.r@company.com',
    assignedTo: 'user-1',
    assignedToName: 'Sarah Chen',
    createdAt: twoDaysAgo.toISOString(),
    updatedAt: oneDayAgo.toISOString(),
    dueDate: addDays(twoDaysAgo, 2).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: addHours(twoDaysAgo, 1).toISOString(),
    responseTime: 60,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '15',
    ticketNumber: 'TKT-015',
    title: 'General inquiry about pricing',
    description: 'Can you explain the different pricing tiers?',
    status: 'waiting',
    priority: 'low',
    category: 'general',
    tags: ['pricing', 'sales'],
    customerName: 'Jessica White',
    customerEmail: 'jessica.w@prospect.com',
    assignedTo: null,
    assignedToName: null,
    createdAt: oneDayAgo.toISOString(),
    updatedAt: oneDayAgo.toISOString(),
    dueDate: addDays(oneDayAgo, 3).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: addHours(oneDayAgo, 4).toISOString(),
    responseTime: 240,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '16',
    ticketNumber: 'TKT-016',
    title: 'Certificate expired on production',
    description: 'SSL certificate expired and needs immediate renewal.',
    status: 'resolved',
    priority: 'critical',
    category: 'bug',
    tags: ['critical', 'ssl', 'infrastructure'],
    customerName: 'William Clark',
    customerEmail: 'william.c@ops.com',
    assignedTo: 'user-3',
    assignedToName: 'David Lee',
    createdAt: new Date(now.getTime() - 48 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
    dueDate: new Date(now.getTime() - 48 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(),
    closedAt: null,
    firstResponseAt: new Date(now.getTime() - 48 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
    responseTime: 15,
    resolutionTime: 24 * 60,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '17',
    ticketNumber: 'TKT-017',
    title: 'CSV import failing on large files',
    description: 'Cannot import CSV files larger than 10MB.',
    status: 'new',
    priority: 'medium',
    category: 'bug',
    tags: ['import', 'limitation'],
    customerName: 'Rachel Green',
    customerEmail: 'rachel.g@data.com',
    assignedTo: null,
    assignedToName: null,
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    dueDate: addHours(new Date(now.getTime() - 2 * 60 * 60 * 1000), 48).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: null,
    responseTime: null,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '18',
    ticketNumber: 'TKT-018',
    title: 'Request: Multi-language support',
    description: 'Need support for Spanish and French translations.',
    status: 'waiting',
    priority: 'medium',
    category: 'feature',
    tags: ['localization', 'feature-request'],
    customerName: 'Miguel Hernandez',
    customerEmail: 'miguel.h@international.com',
    assignedTo: 'user-2',
    assignedToName: 'Michael Johnson',
    createdAt: fourDaysAgo.toISOString(),
    updatedAt: oneDayAgo.toISOString(),
    dueDate: addDays(fourDaysAgo, 7).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: addHours(fourDaysAgo, 2).toISOString(),
    responseTime: 120,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '19',
    ticketNumber: 'TKT-019',
    title: 'Session timeout too short',
    description: 'Getting logged out too quickly during work sessions.',
    status: 'resolved',
    priority: 'low',
    category: 'support',
    tags: ['session', 'ux'],
    customerName: 'Susan Martinez',
    customerEmail: 'susan.m@company.com',
    assignedTo: 'user-1',
    assignedToName: 'Sarah Chen',
    createdAt: sixDaysAgo.toISOString(),
    updatedAt: fourDaysAgo.toISOString(),
    dueDate: addDays(sixDaysAgo, 3).toISOString(),
    resolvedAt: fourDaysAgo.toISOString(),
    closedAt: null,
    firstResponseAt: addHours(sixDaysAgo, 3).toISOString(),
    responseTime: 180,
    resolutionTime: 2 * 24 * 60,
    isDeleted: false,
    deletedAt: null,
  },
  {
    id: '20',
    ticketNumber: 'TKT-020',
    title: 'Need refund for subscription',
    description: 'Requesting refund for last month due to service issues.',
    status: 'new',
    priority: 'high',
    category: 'billing',
    tags: ['refund', 'billing'],
    customerName: 'George Thompson',
    customerEmail: 'george.t@business.com',
    assignedTo: null,
    assignedToName: null,
    createdAt: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
    dueDate: addHours(new Date(now.getTime() - 3 * 60 * 60 * 1000), 24).toISOString(),
    resolvedAt: null,
    closedAt: null,
    firstResponseAt: null,
    responseTime: null,
    resolutionTime: null,
    isDeleted: false,
    deletedAt: null,
  },
];
