import { TimeEntry } from '@/types/employee';
import { addDays, format, subDays } from 'date-fns';

const today = new Date();

export const mockTimeEntries: TimeEntry[] = [
  // John Smith (EMP001) - Current week
  {
    id: 'TE001',
    employeeId: 'EMP001',
    date: format(subDays(today, 4), 'yyyy-MM-dd'),
    clockIn: '09:00',
    clockOut: '17:30',
    breakMinutes: 60,
    totalHours: 7.5,
    status: 'completed',
  },
  {
    id: 'TE002',
    employeeId: 'EMP001',
    date: format(subDays(today, 3), 'yyyy-MM-dd'),
    clockIn: '08:55',
    clockOut: '17:15',
    breakMinutes: 60,
    totalHours: 7.33,
    status: 'completed',
  },
  {
    id: 'TE003',
    employeeId: 'EMP001',
    date: format(subDays(today, 2), 'yyyy-MM-dd'),
    clockIn: '09:05',
    clockOut: '18:00',
    breakMinutes: 60,
    totalHours: 7.92,
    status: 'completed',
  },
  {
    id: 'TE004',
    employeeId: 'EMP001',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    clockIn: '09:00',
    clockOut: '17:00',
    breakMinutes: 60,
    totalHours: 7,
    status: 'completed',
  },
  {
    id: 'TE005',
    employeeId: 'EMP001',
    date: format(today, 'yyyy-MM-dd'),
    clockIn: '09:00',
    clockOut: null,
    breakMinutes: 0,
    totalHours: 0,
    status: 'clocked-in',
  },

  // Michael Chen (EMP003) - Current week
  {
    id: 'TE010',
    employeeId: 'EMP003',
    date: format(subDays(today, 4), 'yyyy-MM-dd'),
    clockIn: '09:15',
    clockOut: '17:45',
    breakMinutes: 60,
    totalHours: 7.5,
    status: 'completed',
  },
  {
    id: 'TE011',
    employeeId: 'EMP003',
    date: format(subDays(today, 3), 'yyyy-MM-dd'),
    clockIn: '09:00',
    clockOut: '17:30',
    breakMinutes: 60,
    totalHours: 7.5,
    status: 'completed',
  },
  {
    id: 'TE012',
    employeeId: 'EMP003',
    date: format(subDays(today, 2), 'yyyy-MM-dd'),
    clockIn: '09:10',
    clockOut: '18:10',
    breakMinutes: 60,
    totalHours: 8,
    status: 'completed',
  },
  {
    id: 'TE013',
    employeeId: 'EMP003',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    clockIn: '09:05',
    clockOut: '17:35',
    breakMinutes: 60,
    totalHours: 7.5,
    status: 'completed',
  },
  {
    id: 'TE014',
    employeeId: 'EMP003',
    date: format(today, 'yyyy-MM-dd'),
    clockIn: '09:00',
    clockOut: null,
    breakMinutes: 0,
    totalHours: 0,
    status: 'clocked-in',
  },

  // Sarah Johnson (EMP002) - Current week
  {
    id: 'TE020',
    employeeId: 'EMP002',
    date: format(subDays(today, 4), 'yyyy-MM-dd'),
    clockIn: '10:00',
    clockOut: '18:00',
    breakMinutes: 60,
    totalHours: 7,
    status: 'completed',
  },
  {
    id: 'TE021',
    employeeId: 'EMP002',
    date: format(subDays(today, 3), 'yyyy-MM-dd'),
    clockIn: '10:05',
    clockOut: '18:05',
    breakMinutes: 60,
    totalHours: 7,
    status: 'completed',
  },
  {
    id: 'TE022',
    employeeId: 'EMP002',
    date: format(subDays(today, 2), 'yyyy-MM-dd'),
    clockIn: '09:55',
    clockOut: '17:55',
    breakMinutes: 60,
    totalHours: 7,
    status: 'completed',
  },
  {
    id: 'TE023',
    employeeId: 'EMP002',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    clockIn: '10:00',
    clockOut: '18:00',
    breakMinutes: 60,
    totalHours: 7,
    status: 'completed',
  },
  {
    id: 'TE024',
    employeeId: 'EMP002',
    date: format(today, 'yyyy-MM-dd'),
    clockIn: '10:00',
    clockOut: null,
    breakMinutes: 0,
    totalHours: 0,
    status: 'clocked-in',
  },

  // Emily Davis (EMP004) - Current week
  {
    id: 'TE030',
    employeeId: 'EMP004',
    date: format(subDays(today, 4), 'yyyy-MM-dd'),
    clockIn: '08:00',
    clockOut: '16:30',
    breakMinutes: 60,
    totalHours: 7.5,
    status: 'completed',
  },
  {
    id: 'TE031',
    employeeId: 'EMP004',
    date: format(subDays(today, 3), 'yyyy-MM-dd'),
    clockIn: '08:05',
    clockOut: '16:35',
    breakMinutes: 60,
    totalHours: 7.5,
    status: 'completed',
  },
  {
    id: 'TE032',
    employeeId: 'EMP004',
    date: format(subDays(today, 2), 'yyyy-MM-dd'),
    clockIn: '08:00',
    clockOut: '16:00',
    breakMinutes: 60,
    totalHours: 7,
    status: 'completed',
  },
  {
    id: 'TE033',
    employeeId: 'EMP004',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    clockIn: '08:10',
    clockOut: '16:40',
    breakMinutes: 60,
    totalHours: 7.5,
    status: 'completed',
  },
  {
    id: 'TE034',
    employeeId: 'EMP004',
    date: format(today, 'yyyy-MM-dd'),
    clockIn: '08:00',
    clockOut: null,
    breakMinutes: 0,
    totalHours: 0,
    status: 'clocked-in',
  },

  // Maria Garcia (EMP010) - Night shift worker
  {
    id: 'TE040',
    employeeId: 'EMP010',
    date: format(subDays(today, 4), 'yyyy-MM-dd'),
    clockIn: '14:00',
    clockOut: '22:30',
    breakMinutes: 60,
    totalHours: 7.5,
    status: 'completed',
  },
  {
    id: 'TE041',
    employeeId: 'EMP010',
    date: format(subDays(today, 3), 'yyyy-MM-dd'),
    clockIn: '14:00',
    clockOut: '22:00',
    breakMinutes: 60,
    totalHours: 7,
    status: 'completed',
  },
  {
    id: 'TE042',
    employeeId: 'EMP010',
    date: format(subDays(today, 2), 'yyyy-MM-dd'),
    clockIn: '14:10',
    clockOut: '22:40',
    breakMinutes: 60,
    totalHours: 7.5,
    status: 'completed',
  },
  {
    id: 'TE043',
    employeeId: 'EMP010',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    clockIn: '14:00',
    clockOut: '22:00',
    breakMinutes: 60,
    totalHours: 7,
    status: 'completed',
  },
  {
    id: 'TE044',
    employeeId: 'EMP010',
    date: format(today, 'yyyy-MM-dd'),
    clockIn: '14:00',
    clockOut: null,
    breakMinutes: 0,
    totalHours: 0,
    status: 'clocked-in',
  },
];
