import { Product, CategoryInfo, DailySpecial } from '@/types/product';

// Category definitions
export const categories: CategoryInfo[] = [
  {
    id: 'all',
    name: 'All Products',
    description: 'Browse our complete selection',
  },
  {
    id: 'viennoiseries',
    name: 'Viennoiseries',
    icon: '🥐',
    description: 'Classic French pastries',
  },
  {
    id: 'breads',
    name: 'Breads',
    icon: '🥖',
    description: 'Artisan baked breads',
  },
  {
    id: 'pastries',
    name: 'Pastries',
    icon: '🧁',
    description: 'Sweet delights',
  },
  {
    id: 'cakes',
    name: 'Cakes',
    icon: '🎂',
    description: 'Celebration cakes',
  },
  {
    id: 'specials',
    name: 'Daily Specials',
    icon: '⭐',
    description: 'Today\'s featured items',
  },
];

// Mock product data
export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Croissant',
    description: 'Buttery, flaky, and perfectly golden. Made with French butter and traditional lamination techniques.',
    price: 3.50,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    category: 'viennoiseries',
    isNew: false,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'dairy'],
    ingredients: ['flour', 'butter', 'yeast', 'sugar', 'salt', 'milk'],
  },
  {
    id: '2',
    name: 'Pain au Chocolat',
    description: 'Flaky croissant dough wrapped around rich dark chocolate batons.',
    price: 4.00,
    image: 'https://images.unsplash.com/photo-1623334044303-241021148842?auto=format&fit=crop&w=800&q=80',
    category: 'viennoiseries',
    isNew: false,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'dairy'],
    ingredients: ['flour', 'butter', 'dark chocolate', 'yeast', 'sugar', 'salt'],
  },
  {
    id: '3',
    name: 'Baguette Traditionnelle',
    description: 'Crispy crust, soft interior. The iconic French bread baked fresh daily.',
    price: 2.75,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    category: 'breads',
    isSpecial: true,
    dietaryTags: ['vegan'],
    allergens: ['gluten'],
    ingredients: ['flour', 'water', 'salt', 'yeast'],
    bakedToday: true,
    limitedQuantity: true,
    stockRemaining: 8,
  },
  {
    id: '4',
    name: 'Almond Croissant',
    description: 'Croissant filled with almond cream and topped with sliced almonds.',
    price: 4.50,
    image: 'https://images.unsplash.com/photo-1549903072-7e6e0bedb7fb?auto=format&fit=crop&w=800&q=80',
    category: 'viennoiseries',
    isNew: true,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'dairy', 'nuts'],
    ingredients: ['flour', 'butter', 'almonds', 'almond cream', 'sugar', 'eggs'],
    bakedToday: true,
  },
  {
    id: '5',
    name: 'Pain de Campagne',
    description: 'Rustic country bread with a thick crust and chewy crumb.',
    price: 5.50,
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=800&q=80',
    category: 'breads',
    isNew: false,
    dietaryTags: ['vegan'],
    allergens: ['gluten'],
    ingredients: ['flour', 'whole wheat flour', 'water', 'salt', 'sourdough starter'],
  },
  {
    id: '6',
    name: 'Éclair au Chocolat',
    description: 'Light choux pastry filled with chocolate cream and topped with glossy chocolate icing.',
    price: 5.00,
    image: 'https://images.unsplash.com/photo-1612203985729-70726954388c?auto=format&fit=crop&w=800&q=80',
    category: 'pastries',
    isNew: false,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'dairy', 'eggs'],
    ingredients: ['flour', 'butter', 'eggs', 'chocolate', 'cream', 'sugar'],
  },
  {
    id: '7',
    name: 'Tarte aux Fraises',
    description: 'Fresh strawberry tart with vanilla pastry cream on a buttery sweet crust.',
    price: 6.50,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    category: 'pastries',
    isSpecial: true,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'dairy', 'eggs'],
    ingredients: ['flour', 'butter', 'strawberries', 'cream', 'vanilla', 'sugar', 'eggs'],
    limitedQuantity: true,
    stockRemaining: 3,
    bakedToday: true,
  },
  {
    id: '8',
    name: 'Mille-Feuille',
    description: 'Layers of crispy puff pastry with vanilla cream, topped with fondant icing.',
    price: 6.00,
    image: 'https://images.unsplash.com/photo-1519915212116-7cfef71f1d3e?auto=format&fit=crop&w=800&q=80',
    category: 'pastries',
    isNew: true,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'dairy', 'eggs'],
    ingredients: ['puff pastry', 'pastry cream', 'fondant', 'vanilla', 'sugar'],
  },
  {
    id: '9',
    name: 'Brioche Dorée',
    description: 'Rich, golden brioche with a tender crumb. Perfect for breakfast.',
    price: 7.00,
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=800&q=80',
    category: 'breads',
    isNew: false,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'dairy', 'eggs'],
    ingredients: ['flour', 'butter', 'eggs', 'milk', 'sugar', 'yeast', 'salt'],
  },
  {
    id: '10',
    name: 'Macaron Assortment',
    description: 'Box of 6 delicate French macarons in assorted flavors.',
    price: 12.00,
    image: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&w=800&q=80',
    category: 'pastries',
    isNew: true,
    dietaryTags: ['vegetarian', 'gluten-free'],
    allergens: ['dairy', 'eggs', 'nuts'],
    ingredients: ['almond flour', 'sugar', 'egg whites', 'butter', 'cream', 'flavorings'],
  },
  {
    id: '11',
    name: 'Sourdough Boule',
    description: 'Artisan sourdough with a crispy crust and open crumb structure.',
    price: 8.00,
    image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80',
    category: 'breads',
    isSpecial: true,
    dietaryTags: ['vegan'],
    allergens: ['gluten'],
    ingredients: ['flour', 'water', 'salt', 'sourdough starter'],
    bakedToday: true,
    limitedQuantity: true,
    stockRemaining: 5,
  },
  {
    id: '12',
    name: 'Tarte Tatin',
    description: 'Upside-down caramelized apple tart with buttery pastry.',
    price: 7.50,
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    category: 'cakes',
    isNew: false,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'dairy'],
    ingredients: ['apples', 'butter', 'sugar', 'puff pastry', 'cinnamon'],
  },
];

// Daily special (mock data)
export const dailySpecial: DailySpecial = {
  id: 'special-1',
  product: products[2], // Baguette
  discount: 15,
  endsAt: new Date(Date.now() + 8 * 60 * 60 * 1000), // 8 hours from now
  description: 'Freshly baked this morning! Get 15% off our classic baguette.',
};

// Bakery information
export const bakeryInfo = {
  name: 'La Boulangerie Française',
  tagline: 'Freshly Baked Daily',
  story: 'For over 30 years, our family bakery has been crafting authentic French breads and pastries using traditional techniques passed down through generations. Every morning, our artisan bakers begin work before dawn to ensure you receive the freshest, most authentic French baked goods.',
  hours: {
    monday: '7:00 AM - 7:00 PM',
    tuesday: '7:00 AM - 7:00 PM',
    wednesday: '7:00 AM - 7:00 PM',
    thursday: '7:00 AM - 7:00 PM',
    friday: '7:00 AM - 8:00 PM',
    saturday: '6:00 AM - 8:00 PM',
    sunday: '6:00 AM - 6:00 PM',
  },
  address: '123 Rue de la Paix, Paris District',
  phone: '+1 (555) 123-4567',
  email: 'hello@laboulangerie.com',
  // Map coordinates (Paris area - will be random on each page load for demo)
  coordinates: {
    lat: 48.8566,
    lng: 2.3522,
  } as { lat: number; lng: number },
};
